package applapangan;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author tobyz
 */
public class MenuUtama extends javax.swing.JFrame {

    private Dimension screensize;

    public MenuUtama() {
        initComponents();
        this.setResizable(false);
        screensize = Toolkit.getDefaultToolkit().getScreenSize();
        setLocation((screensize.width / 2) - (getSize().width / 2), (screensize.height / 2) - (getSize().height / 2));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        DPUtama = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        MenuBar = new javax.swing.JMenuBar();
        MProgram = new javax.swing.JMenu();
        MiLogout = new javax.swing.JMenuItem();
        MMaster = new javax.swing.JMenu();
        MiPelanggan = new javax.swing.JMenuItem();
        MiTim = new javax.swing.JMenuItem();
        MiUser = new javax.swing.JMenuItem();
        MiLapangan = new javax.swing.JMenuItem();
        MTransaksi = new javax.swing.JMenu();
        MiPenyewaan = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Penyewaan [Beta]");

        javax.swing.GroupLayout DPUtamaLayout = new javax.swing.GroupLayout(DPUtama);
        DPUtama.setLayout(DPUtamaLayout);
        DPUtamaLayout.setHorizontalGroup(
            DPUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1357, Short.MAX_VALUE)
        );
        DPUtamaLayout.setVerticalGroup(
            DPUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 716, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel1.setText("Nama Pengguna :");

        lblUser.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblUser.setText("user");

        lblID.setForeground(new java.awt.Color(240, 240, 240));
        lblID.setText("id");

        MenuBar.setForeground(new java.awt.Color(0, 102, 102));
        MenuBar.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N

        MProgram.setText("Program");

        MiLogout.setText("Logout");
        MiLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiLogoutActionPerformed(evt);
            }
        });
        MProgram.add(MiLogout);

        MenuBar.add(MProgram);

        MMaster.setText("Master");

        MiPelanggan.setText("Pelanggan");
        MiPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiPelangganActionPerformed(evt);
            }
        });
        MMaster.add(MiPelanggan);

        MiTim.setText("Tim");
        MiTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiTimActionPerformed(evt);
            }
        });
        MMaster.add(MiTim);

        MiUser.setText("User");
        MiUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiUserActionPerformed(evt);
            }
        });
        MMaster.add(MiUser);

        MiLapangan.setText("Lapangan");
        MiLapangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiLapanganActionPerformed(evt);
            }
        });
        MMaster.add(MiLapangan);

        MenuBar.add(MMaster);

        MTransaksi.setText("Transaksi");

        MiPenyewaan.setText("Penyewaan");
        MiPenyewaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiPenyewaanActionPerformed(evt);
            }
        });
        MTransaksi.add(MiPenyewaan);

        MenuBar.add(MTransaksi);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DPUtama)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUser)
                .addGap(501, 501, 501)
                .addComponent(lblID)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(DPUtama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblUser)
                    .addComponent(lblID))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MiLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiLogoutActionPerformed
        FLogin login = new FLogin();
        if (JOptionPane.showConfirmDialog(null, "Apakah Anda yakin akan keluar?", "Keluar", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            login.show();
            this.dispose();
        }
    }//GEN-LAST:event_MiLogoutActionPerformed

    private void MiUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiUserActionPerformed
        FMUser user = new FMUser();
        DPUtama.add(user);
        user.setVisible(true);
    }//GEN-LAST:event_MiUserActionPerformed

    private void MiPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiPelangganActionPerformed
        FMPelanggan pelanggan = new FMPelanggan();
        DPUtama.add(pelanggan);
        pelanggan.setVisible(true);
        pelanggan.lblID.setText(this.lblID.getText());
    }//GEN-LAST:event_MiPelangganActionPerformed

    private void MiPenyewaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiPenyewaanActionPerformed
        FTPenyewaan sewa = new FTPenyewaan();
        DPUtama.add(sewa);
        sewa.setVisible(true);
        sewa.lblID.setText(this.lblID.getText());
    }//GEN-LAST:event_MiPenyewaanActionPerformed

    private void MiTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiTimActionPerformed
        FMTim tim = new FMTim();
        DPUtama.add(tim);
        tim.setVisible(true);
        tim.lblID.setText(this.lblID.getText());
    }//GEN-LAST:event_MiTimActionPerformed

    private void MiLapanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiLapanganActionPerformed
        FMLapangan lapangan = new FMLapangan();
        DPUtama.add(lapangan);
        lapangan.setVisible(true);
        lapangan.lblID.setText(this.lblID.getText());
    }//GEN-LAST:event_MiLapanganActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JDesktopPane DPUtama;
    public javax.swing.JMenu MMaster;
    private javax.swing.JMenu MProgram;
    private javax.swing.JMenu MTransaksi;
    public javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenuItem MiLapangan;
    private javax.swing.JMenuItem MiLogout;
    private javax.swing.JMenuItem MiPelanggan;
    public javax.swing.JMenuItem MiPenyewaan;
    private javax.swing.JMenuItem MiTim;
    public javax.swing.JMenuItem MiUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    public javax.swing.JLabel lblID;
    public javax.swing.JLabel lblUser;
    // End of variables declaration//GEN-END:variables
}
